### ISSUE TITLE
Error to be catch when XML source unavailable

### ISSUE THREAD

**Issue by oncleben31** [oncleben31/vigilancemeteo#1]
```
Update for sensor.vigilance_meteo fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/alertemeteo.py", line 99, in update
    self._watchedDepartment.miseAJourEtat()
  File "/config/deps/lib/python3.6/site-packages/vigilancemeteo/vigilance.py", line 107, in miseAJourEtat
    tree = etree.parse(ZoneAlerte.URL_VIGILANCE_METEO)
  File "src/lxml/etree.pyx", line 3424, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1840, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1866, in lxml.etree._parseDocumentFromURL
  File "src/lxml/parser.pxi", line 1770, in lxml.etree._parseDocFromFile
  File "src/lxml/parser.pxi", line 1163, in lxml.etree._BaseParser._parseDocFromFile
  File "src/lxml/parser.pxi", line 601, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 711, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
OSError: Error reading file 'http://vigilance.meteofrance.com/data/NXFR33_LFPW_.xml': failed to load external entity "http://vigilance.meteofrance.com/data/NXFR33_LFPW_.xml"
```

**Comment by oncleben31** [comment]
Closed with #2
